In [1]:
import pandas as pd

# 5.1 Introduction to pandas Data Structures

### Series

In [2]:
obj = pd.Series([4, 7, -5, 3])

In [3]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

And so on...

In [4]:
obj.values

array([ 4,  7, -5,  3])

In [7]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [11]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])


In [12]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [13]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [14]:
obj2['a']

-5

In [15]:
obj2['d'] = 6

In [16]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [17]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [18]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [20]:
np.exp(obj2)


NameError: name 'np' is not defined

In [21]:
'b' in obj2

True

In [22]:
'e' in obj2

False

In [23]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [24]:
obj3 = pd.Series(sdata)

In [25]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [26]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [27]:
obj4 = pd.Series(sdata, index=states)

In [28]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [29]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [30]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [31]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [32]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [33]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [34]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [35]:
obj4.name = 'population'

In [36]:
obj4.index.name = 'state'

In [37]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [38]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [39]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [40]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [42]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [43]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [44]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [45]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [46]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four',
'five', 'six'])

In [47]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [48]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [49]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [50]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [51]:
frame2.loc['three']


year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [52]:
frame2['debt'] = 16.5

In [53]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [56]:
frame2['debt'] = np.arange(6.)

NameError: name 'np' is not defined

In [57]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [58]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [59]:
frame2['debt'] = val

In [60]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [61]:
frame2['eastern'] = frame2.state == 'Ohio'


In [62]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [63]:
del frame2['eastern']


In [64]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [65]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
....: 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [66]:
frame3 = pd.DataFrame(pop)


In [67]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [68]:
 frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [69]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [70]:
pdata = {'Ohio': frame3['Ohio'][:-1], 'Nevada': frame3['Nevada'][:2]}


In [72]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [73]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [74]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [75]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [76]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [95]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [96]:
index = obj.index


In [97]:
index

Index(['a', 'b', 'c'], dtype='object')

In [98]:
index[1:]


Index(['b', 'c'], dtype='object')

In [101]:
labels = pd.Index(np.arange(3))

NameError: name 'np' is not defined

In [102]:
labels

NameError: name 'labels' is not defined

In [103]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

NameError: name 'labels' is not defined

In [104]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [105]:
obj2.index is labels

NameError: name 'labels' is not defined

In [106]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [107]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [108]:
'Ohio' in frame3.columns

True

In [109]:
2003 in frame3.index

False

In [110]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [111]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [112]:
In [91]: obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [113]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [114]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [115]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [116]:
 obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [117]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [118]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [119]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])

NameError: name 'np' is not defined

In [120]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [121]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [122]:
frame2

state  year  pop
a   NaN   NaN  NaN
b   NaN   NaN  NaN
c   NaN   NaN  NaN
d   NaN   NaN  NaN

In [123]:
states = ['Texas', 'Utah', 'California']


In [124]:
frame.reindex(columns=states)

Texas  Utah  California
0    NaN   NaN         NaN
1    NaN   NaN         NaN
2    NaN   NaN         NaN
3    NaN   NaN         NaN
4    NaN   NaN         NaN
5    NaN   NaN         NaN

In [125]:
frame.loc[['a', 'b', 'c', 'd'], states]

KeyError: "None of [Index(['a', 'b', 'c', 'd'], dtype='object')] are in the [index]"

In [126]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

NameError: name 'np' is not defined

In [127]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [128]:
new_obj = obj.drop('c')

In [129]:
new_obj

d    4.5
b    7.2
a   -5.3
dtype: float64

In [130]:
obj.drop(['d', 'c'])

b    7.2
a   -5.3
dtype: float64

In [133]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

NameError: name 'np' is not defined

In [134]:
data

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [135]:
data.drop(['Colorado', 'Ohio'])

AttributeError: 'dict' object has no attribute 'drop'

In [136]:
data.drop('two', axis=1)

AttributeError: 'dict' object has no attribute 'drop'

In [137]:
 data.drop(['two', 'four'], axis='columns')

AttributeError: 'dict' object has no attribute 'drop'

In [138]:
obj.drop('c', inplace=True)

In [139]:
obj

d    4.5
b    7.2
a   -5.3
dtype: float64

In [140]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])


NameError: name 'np' is not defined

In [141]:
obj

d    4.5
b    7.2
a   -5.3
dtype: float64

In [142]:
obj['b]']

KeyError: 'b]'

In [143]:
obj[1]

7.2

In [144]:
obj[2:4]

a   -5.3
dtype: float64

In [145]:
obj[['b', 'a', 'd']]

b    7.2
a   -5.3
d    4.5
dtype: float64

In [146]:
 obj[[1, 3]]

IndexError: positional indexers are out-of-bounds

In [147]:
obj[obj < 2]

a   -5.3
dtype: float64

In [148]:
obj['b':'c']

Series([], dtype: float64)

In [149]:
obj['b':'c'] = 5

In [150]:
obj

d    4.5
b    7.2
a   -5.3
dtype: float64

In [154]:

data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

NameError: name 'np' is not defined

In [155]:
data

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [156]:
data['two']

KeyError: 'two'

In [157]:
 data[['three', 'one']]

TypeError: unhashable type: 'list'

In [158]:
data[:2]

TypeError: unhashable type: 'slice'

In [159]:
data[data['three'] > 5]

KeyError: 'three'

In [160]:
data

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [161]:
data[data < 5] = 0

TypeError: '<' not supported between instances of 'dict' and 'int'

In [162]:
data

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [163]:
 data.loc['Colorado', ['two', 'three']]

AttributeError: 'dict' object has no attribute 'loc'

In [164]:
data.iloc[2, [3, 0, 1]]

AttributeError: 'dict' object has no attribute 'iloc'

In [165]:
 data.iloc[2]

AttributeError: 'dict' object has no attribute 'iloc'

In [166]:
data.iloc[[1, 2], [3, 0, 1]]

AttributeError: 'dict' object has no attribute 'iloc'

In [167]:
 data.loc[:'Utah', 'two']

AttributeError: 'dict' object has no attribute 'loc'

In [168]:
data.iloc[:, :3][data.three > 5]

AttributeError: 'dict' object has no attribute 'iloc'

In [170]:
ser = pd.Series(np.arange(3.)) 
ser
ser[-1]

NameError: name 'np' is not defined

In [172]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

NameError: name 'np' is not defined

In [173]:
 ser2[-1]

NameError: name 'ser2' is not defined

In [174]:
ser[:1]

NameError: name 'ser' is not defined

In [175]:
ser[:1]

NameError: name 'ser' is not defined

In [176]:
ser.iloc[:1]

NameError: name 'ser' is not defined

In [177]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [178]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],index=['a', 'c', 'e', 'f', 'g'])

In [179]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [180]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [181]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [185]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'), 
                   index=['Ohio', 'Texas', 'Colorado'])

NameError: name 'np' is not defined

In [186]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

NameError: name 'np' is not defined

In [187]:
df1

NameError: name 'df1' is not defined